-- 코드를 입력하세요

WITH DATETIME AS (
    SELECT AI.ANIMAL_ID, AI.NAME, DATEDIFF(AO.DATETIME, AI.DATETIME) AS DATETIME
    FROM ANIMAL_INS AI LEFT JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID=AO.ANIMAL_ID
    ORDER BY DATETIME DESC
    LIMIT 2
)

SELECT ANIMAL_ID, NAME
FROM DATETIME;