-- 2025.10.29

SELECT FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
      FROM(
        SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER FROM JULY) U
      GROUP BY FLAVOR) T
ORDER BY TOTAL DESC
LIMIT 3;