-- 코드를 입력하세요

SELECT 
    CASE
        WHEN HOUR(DATETIME) >= 7 AND HOUR(DATETIME) < 8 THEN '7'
        WHEN HOUR(DATETIME) >= 8 AND HOUR(DATETIME) < 9 THEN '8'
        WHEN HOUR(DATETIME) >= 9 AND HOUR(DATETIME) < 10 THEN '9' 
        WHEN HOUR(DATETIME) >= 10 AND HOUR(DATETIME) < 11 THEN '10'
        WHEN HOUR(DATETIME) >= 11 AND HOUR(DATETIME) < 12 THEN '11'
        WHEN HOUR(DATETIME) >= 12 AND HOUR(DATETIME) < 13 THEN '12'
        WHEN HOUR(DATETIME) >= 13 AND HOUR(DATETIME) < 14 THEN '13'
        WHEN HOUR(DATETIME) >= 14 AND HOUR(DATETIME) < 15 THEN '14'
        WHEN HOUR(DATETIME) >= 15 AND HOUR(DATETIME) < 16 THEN '15'
        WHEN HOUR(DATETIME) >= 16 AND HOUR(DATETIME) < 17 THEN '16'
        WHEN HOUR(DATETIME) >= 17 AND HOUR(DATETIME) < 18 THEN '17'
        WHEN HOUR(DATETIME) >= 18 AND HOUR(DATETIME) < 19 THEN '18'
        WHEN HOUR(DATETIME) >= 19 AND HOUR(DATETIME) < 20 THEN '19'
    END AS HOUR, count(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR >= 9 AND HOUR < 20
ORDER BY HOUR(DATETIME) ASC;